services:
  velhos-ditados-api:
    build: .
    ports:
      - "7001:7001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=VelhosDitadosDb;User=sa;Password=YourPassword123!;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - ASPNETCORE_URLS=http://+:7001
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: